### ISSUE TITLE
Compile to UMD for direct usage on web

### ISSUE THREAD

**Issue by michaelgira23** [MyMICDS/MyMICDS-SDK#28]
We want the option to directly use the SDK on web without needing a build tool like Webpack. We should have another file (`umd.js`) that compiles the SDK to UMD and bundle as many dependencies as we can. That way, we can use something like [UNPKG](https://unpkg.com) for convenient usage directly on web.

I already have a branch with a prototype on https://github.com/MyMICDS/MyMICDS-SDK/commit/13b7d0a357d169285f72416c68c237a3f5f8c563, but RxJS pipe operators not fully working.

**Comment by nickbclifford** [comment]
Seems like potentially a peer dependency issue - I suspect if we remove `rxjs` from [our direct dependencies](https://github.com/MyMICDS/MyMICDS-SDK/blob/master/package.json#L46) and [add it as a peer dependency in Webpack](https://webpack.js.org/guides/author-libraries/#externalize-lodash), it might fix the pipe issues.
